@startuml
'https://plantuml.com/activity-diagram-beta

start
:Ввод числа n<
:Переменные even odd]

while (n > 0)
  :num = n // 10]
  :n = n % 10]
  :even++ or odd++]
endwhile

:print(even, odd)]

stop

@enduml
